#!/usr/bin/env bash
# ==============================================================================
# Start smbd service
# ==============================================================================
#samba-tool domain schemaupgrade
bashio::log.info "Starting Samba4 Active Directory..."
exec /usr/sbin/samba -i
